### ISSUE TITLE
Scroll bars are missing

### ISSUE THREAD

**Issue by SpicyShino** [gmariani/minerva#74] opened 2018-01-31 19:50 UTC
It's cool that you're still updating the program, but without scroll bars it's practically unusable on larger files.

**Comment by SpicyShino** [comment] 2018-01-31 19:55
Just tested and this seems to be an issue on FireFox but not Chrome.

**Comment by gmariani** [comment] 2018-01-31 22:10
Could you upload a sample file for me to test with?

**Comment by Celti** [comment] 2018-02-01 03:34
You can reproduce with any SOL that has enough items to overflow your viewport. I'm not quite sure what the difference is between Chrome and Firefox on this (I'd expect them *both* to break), but you can naively fix it by setting `overflow: auto;` on `#wrapper`. This looks ugly on smaller (720p) screens, however, thanks to the size of the header and footer; I'd prefer setting `max-height: 100vh;` on `#wrapper` and `overflow: auto;` on `#application`, which will let the header and footer scroll out of view when necessary while keeping everything accessible.

**Comment by gmariani** [comment] 2018-02-01 04:03
I think i have a fix for this, might wait a while before pushing out incase people find some more issues. And thanks for the compliment. I realize Flash is going away, but this is still a fun project and people still use it. So why not.

**Comment by gmariani** [comment] 2018-02-01 04:12
ok I think i have it fixed, please check it out: https://mariani.life/projects/minerva_4.2.1/

**Comment by Celti** [comment] 2018-02-01 04:18
Yep, that fixes it for me.

**Comment by gmariani** [comment] 2018-03-04 14:07
Fixed in 4.2.1

**Closed by gmariani** 2018-03-04 14:07 UTC
Labels: bug

**Comment by wyatt8740** [comment] 2018-03-17 03:51
You did a lot more to fix that than you had to in that commit, I think. All you had to do was to add these two lines to the CSS for `#wrapper` in index.html:
```
min-height: 0;
min-width: 0;
```
Not 100% sure why. I only bring it up because I had to deal with this recently myself.
